### ISSUE TITLE
Noob question...

### ISSUE THREAD

**Issue by gep13** [wpillar/atom-trailing-spaces#10]
I am just getting started with Atom, and I have found your package, which gives similar functionality to what I have seen in Sublime Text that I also use.  Is there a way to change the colour of the highlighted section of the line?

Thanks!

**Comment by wpillar** [comment]
Hey @gep13, the package is configured to use an appropriate colour from your chosen theme. To make sure that the highlighted colour does not clash with the background colour for example.

So in short, in order to change the colour of the highlighting in this package, currently you should look at customising your theme and finding the `@background-color-selected` variable and changing it.

**Comment by gep13** [comment]
Thanks for the information, I will take a look :+1:
